services:
  source_db:
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_SOURCE_DB}
      POSTGRES_USER: ${POSTGRES_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SOURCE_PASSWORD}
      POSTGRES_PORT: 5433  
    command: -p 5433  
    volumes:
      - ./dbdata/source:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - "5433:5433"

  destination_db:
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DEST_DB}
      POSTGRES_USER: ${POSTGRES_DEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEST_PASSWORD}
      POSTGRES_PORT: 5434  
    command: -p 5434  
    volumes:
      - ./dbdata/dest:/var/lib/postgresql/data
    ports:
      - "5434:5434"
